Refactoring merge PR (#649)
* Code architecture refactoring and fixing project structure (#612)

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* Added .editorconfig and fixed style according to it (#621)

* added .editorconfig and fixed style according to it

* add issue link to TODO for creator executor

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* PolicyExtractor refactoring & testing (#625)

* Initial extractorExecutor parameters\configuration refactoring + tests setup

* codestyle fixes. created apiclients and separated API + extraction for policy extractor

* review updates

* explicit variable for fixing dotnet build error CS0815

* fix IO.DirectoryNotFoundException in tests

* rename `ToParameterize` properties

* move template creator to Common\Templates\Abstractions

* rename templateCreator to templateGeneratorBase and make it a parent for all creators\extractors

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* add DI to application (#631)

* add DI to application

* cleared entry pointed, deleted reflection, get rid of comman-line library dependencies in business logic code

* review +build fix

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* product-apis extractor refactoring (#636)

* product apis refactoring

* launchsettings.json rollback

* rename service api products extractor

* global renaming, fix PR review

* rename product-apis response and properties

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* order resources section fields of generated templates (#637)

* order resources section fields of generated templates

* fix comment

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* refactor product extractor, fix logging, rework api-clients (#639)

* refactor product extractor, fix logging, rework api-clients

* rename predefined parameter

* parameter order fix

* rollback launch settings. json

* ignore changes in launch settings json

* make template builder as an injectable service

* exclude template builder extensions

* removed explicit discard

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* fix typos in paths (#640)

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* implement groups extractor (#641)

* implement groups extractor

* [review] duplicated code removal, cleaning tests, fixing namings

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* ApiVersionSet, AuthorizationServer extractors refactoring (#643)

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* make templates generic & refactor api-extractor (#644)

* make templates generic + refactor api-extractor

* runtime bugs fixes

* PR review

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* serialization fixes after refactoring + entry point descriptions added (#645)

* serialization fixes

* provide fully-described outputs and fulfill rdocumentation

* fix required options for commands

* fix spaces

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>

* fix refactoring breaking changes (checked manually)

* remove public pipelines

Co-authored-by: Dmitrii Korolev <dmkorolev@microsoft.com>